//
// Generated by GLSL-optimizer
//

#ifndef CSTUB_GLSL_BUILDER_H
#define CSTUB_GLSL_BUILDER_H

static unsigned char* glsl_shader[] = {
        "SHADER 0 SPECIFIC GOES HERE",
        "SHADER 1 SPECIFIC GOES HERE",
        "SHARED SHADER"
        };

#ifdef GLSL_SINGLE_SHADER
//
// only a single shader used
//

/**
 * Returns the shader with index 0.
 */
#define glslShader(x) glsl_shader[0]

#else //GLSL_SINGLE_SHADER
//
// Multiple shaders used
//

#define GLSL_SHARED_IDX 2
#define GLSL_CONTAINER_LENGTH 29

unsigned char glsl_container[GLSL_CONTAINER_LENGTH];

/**
 * Returns the shader with the specified index or a null pointer if the index is out of range.
 * The returned pointer is only valid until the next invocation of this function.
 * @param index The index of the shader.
 * @return A pointer to the shader.
 */
unsigned char* glslShader(int index);

#endif //GLSL_SINGLE_SHADER

#endif //CSTUB_GLSL_BUILDER_H
