//
// Generated by GLSL-optimizer
//

#include "glsl_builder.h"


#ifndef GLSL_SINGLE_SHADER

unsigned char* glslShader(int index) {
    unsigned char* dst = glsl_container;

    unsigned char* src = glsl_shader[GLSL_SHARED_IDX];
    while (*src != 0) {
        *dst = *src;
        src++;
        dst++;
    }

    src = glsl_shader[index];
    while (*src != 0) {
        *dst = *src;
        src++;
        dst++;
    }

    return glsl_container;
}


#endif // #ifdef GLSL_SINGLE_SHADER