#!/bin/bash

if [ -z "$MINIME_HOME" ]; then
  if  [ -d "$HOME/.minime" ]; then
    MINIME_HOME="$HOME/.minime"
  else
    MINIME_HOME=$(realpath "$(dirname "$0")")
  fi
fi

JAR="$MINIME_HOME/minime-@VERSION@.jar"
if [ ! -f "$JAR" ]; then
  echo "ERROR: Can't find application JAR, please set MINIME_HOME"
  exit 1
fi

case "$1" in
  optimize)
    shift
    java -cp "$JAR" com.tazadum.glsl.cli.OptimizerMain "$@"
    ;;
  compile)
    shift
    java -cp "$JAR" com.tazadum.glsl.cli.CompilerMain "$@"
    ;;
  preprocess)
    shift
    java -cp "$JAR" com.tazadum.glsl.cli.PreprocessorMain "$@"
    ;;
  *)
    echo "ERROR: "
    ;;
esac
